#!/bin/sh

###############################################################################
# Install Xcode command line tools
###############################################################################
echo "Installing Xcode Command Line Tools..."
xcode-select --install

###############################################################################
# Check for Homebrew, else install
###############################################################################
echo "Checking for, or Installing Homebrew..."
if [ -z $(command -v brew) ]; then
    echo "Brew is missing! Installing it..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

###############################################################################
# Make sure we're on latest Homebrew
###############################################################################
echo "Homebrew: updating..."
brew update

###############################################################################
# Upgrade any already-installed formulae
###############################################################################
echo "Homebrew: upgrading..."
brew upgrade

###############################################################################
# Install binaries and other packages
###############################################################################
echo "Homebrew: installing packages..."
brew install ffmpeg
brew install git
brew install httpie
brew install imagemagick
# brew install mackup
brew install mas
# brew install nginx
brew install node
brew install rename
brew install tree
brew install webkit2png
brew install lerna
brew install thefuck
brew install awscli
brew install kubernetes-cli
brew tap weaveworks/tap
brew install weaveworks/tap/eksctl

###############################################################################
# Install iterm2 relative packages
###############################################################################
brew install iterm2 --cask
brew tap homebrew/cask-fonts

# Note: you can use this commnad to find the favorite fonts
# > brew search --cask nerd
brew install --cask font-hack-nerd-font
brew install --cask font-meslo-lg-nerd-font

###############################################################################
# Install applications with Homebrew Cask
###############################################################################
echo "Homebrew Cask: installing apps..."
# brew install 1password --cask
brew install alfred --cask
brew install figma --cask
brew install firefox --cask
# brew install framer-x --cask
brew install github --cask
brew install google-chrome --cask
# brew install hyper --cask
brew install imageoptim --cask
# brew install iina --cask

brew install notion --cask
brew install nucleo --cask
brew install postman --cask
# brew install skype --cask
brew install slack --cask
brew install spectacle --cask
brew install spotify --cask
# brew install sourcetree --cask
brew install tor-browser --cask
brew install transmit --cask
# brew install tunnelbear --cask
brew install visual-studio-code --cask
# brew install whatsapp --cask
# brew install espanso --cask
# brew install via --cask
brew install ngrok --cask
brew install robo-3t --cask
brew install altair-graphql-client --cask

###############################################################################
# Install docker relative packages
###############################################################################
brew install docker --cask
brew install docker-compose
mkdir -p ~/.docker/cli-plugins
ln -sfn /opt/homebrew/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose

###############################################################################
# Install minikube relative packages
###############################################################################
mas install 497799835 # Xcode
brew install kubectl
brew install kind

###############################################################################
# Install applications with mas-cli (Mac App Store CLI)
###############################################################################
echo "mas-cli: installing Mac App Store apps..."
# Line
mas install 539883307
# Amphetamine
mas install 937984704

echo "macOS Config, Dev Tools, Apps are Done Setup!"
